version: '3'
services:
    signup-api:
        image: signup-api
        build: ./api
        command: npm run start
        env_file: .env
        ports:
            - "3000:3000"
        depends_on:
            - "mongo"
        volumes:
            - /usr/src/app/node_modules
            - ./api:/usr/src/app

    mongo:
        image: "mongo"
        ports:
            - "27017:27017"

    adminmongo:
        image: "mrvautin/adminmongo"
        # command: npm start
        ports:
            - "1234:1234"
        environment:
            - HOST=0.0.0.0
